# yaml-language-server: $schema=https://www.schemastore.org/github-action.json

name: "Container-storage BTRFS loopback"
author: "Zeglius"
description: "Mount container-storage in a btrfs loopback for space restrained environments"

inputs:
  target-dir:
    description: "Path to the container-storage directory. Defaults to the user container-storage (~/.local/share/containers)"
    required: false
    default: ""
  mount-opts:
    description: "Mount options for the BTRFS loopback, separated by commas"
    required: false
    default: ""
  loopback-free:
    description: "Percentage of the total space to use for the loopback. Max: 1.0, Min: 0.0"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Mount BTRFS loopback
      id: mount_btrfs
      shell: bash
      continue-on-error: true
      env:
        BTRFS_TARGET_DIR: "${{ inputs.target-dir || '' }}"
        BTRFS_MOUNT_OPTS: "${{ inputs.mount-opts || '' }}"
        BTRFS_LOOPBACK_FREE: "${{ inputs.loopback-free || '0.8' }}"
      run: ${{ github.action_path }}/mount_btrfs.sh

    - name: Fallback to unwanted-software action
      if: steps.mount_btrfs.outcome == 'failure'
      uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
